// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTeploobmenApp.Data;

#nullable disable

namespace WebTeploobmenApp.Migrations
{
    [DbContext(typeof(TeploobmenContext))]
    partial class TeploobmenContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("WebTeploobmenApp.Data.Variant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Av")
                        .HasColumnType("REAL");

                    b.Property<double>("Cm")
                        .HasColumnType("REAL");

                    b.Property<double>("Cr")
                        .HasColumnType("REAL");

                    b.Property<double>("D")
                        .HasColumnType("REAL");

                    b.Property<double>("Gm")
                        .HasColumnType("REAL");

                    b.Property<int>("H0")
                        .HasColumnType("INTEGER");

                    b.Property<double>("T1")
                        .HasColumnType("REAL");

                    b.Property<double>("T2")
                        .HasColumnType("REAL");

                    b.Property<double>("Wr")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
